app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resources([
    'person'            => 'PersonController',
    'country'           => 'CountryController',
    'role'              => 'RoleController',
    'event_category'    => 'EventCategoryController',
    'event_topic'       => 'EventTopicController',
    'event'             => 'EventController',
    'user'              => 'UserController'
    ]);
Route::auth();

Route::get('/home', 'HomeController@index');

app/Person.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Person extends Model
{
    protected $fillable = ['first_name', 'last_name', 'email', 'address1', 'address2', 'postalcode', 'city', 'country_id', 'phone1', 'birthday', 'rating'];
    
    public function country()
    {
        return $this->belongsTo(Country::class);
    }
    
    public function getCountryName()
    {
        $country = Country::where('id', $this->country_id)->firstOrFail();
        return $country->name;
    }
}

app/Http/Controllers/PersonController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Person;
use App\Country;

class PersonController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $people = Person::orderBy('first_name')->orderBy('last_name')->get();
        return view('people.index', compact('people'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $countries = Country::pluck('name', 'id');
        return view('people.create', compact('countries'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Person::create($request->all());
        return redirect()->route('person.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $person = Person::where('id', $id)->firstOrFail();
        return view('people.show', compact('person'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $person = Person::where('id', $id)->firstOrFail();
        $countries = Country::pluck('name', 'id');
        return view('people.edit', compact('person', 'countries'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $person = Person::where('id', $id)->firstOrFail();
        $person->update($request->all());
        return redirect()->route('person.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $person = Person::where('id', $id)->firstOrFail();
        $person->delete();
        return redirect()->route('person.index');
    }
}

resources/views/people/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">Persoon toevoegen</div>

                <div class="panel-body">
                    
                    {!! Form::open(array('route'=>'person.store')) !!}
                    <div class="form-group">
                        {!! Form::label('first_name','Voornaam')!!}
                        {!! Form::text('first_name', null, ['class'=>'form-control']) !!}
                    </div>
                    <div class="form-group">
                        {!! Form::label('last_name','Achternaam')!!}
                        {!! Form::text('last_name', null, ['class'=>'form-control']) !!}
                    </div>
                    <div class="form-group">
                        {!! Form::label('email','Email')!!}
                        {!! Form::text('email', null, ['class'=>'form-control']) !!}
                    </div>
                    <div class="form-group">
                        {!! Form::label('address1','Adres 1')!!}
                        {!! Form::text('address1', null, ['class'=>'form-control']) !!}
                    </div>
                    <div class="form-group">
                        {!! Form::label('address2','Adres 2')!!}
                        {!! Form::text('address2', null,['class'=>'form-control']) !!}
                    </div>
                    <div class="form-group">
                        {!! Form::label('postalcode','Postcode')!!}
                        {!! Form::text('postalcode', null, ['class'=>'form-control']) !!}
                    </div>
                    <div class="form-group">
                        {!! Form::label('city','Stad')!!}
                        {!! Form::text('city', null, ['class'=>'form-control']) !!}
                    </div>
                    <div class="form-group">
                        {!! Form::label('country','Land')!!}
                        {!! Form::select('country_id', $countries, null, ['class'=>'form-control']) !!}
                    </div>
                    <div class="form-group">
                        {!! Form::label('phone1','Telefoon')!!}
                        {!! Form::text('phone1', null, ['class'=>'form-control']) !!}
                    </div>
                    <div class="form-group">
                        {!! Form::label('birthday','Geboortedatum')!!}
                        {!! Form::date('birthday', null, ['class'=>'form-control']) !!}
                    </div>
                    
                    <div class="form-group">
                        {!! Form::button('Create',['type'=>'submit','class'=>'btn btn-primary'])!!}
                        
                    </div>
                    {!! Form::close() !!}
                
              </div>
            </div>
            @if($errors->has())
                <ul class="alert alert-danger">
                @foreach($errors->all() as $error)
                    <li>{{$error}}</li>
                @endforeach
                </ul>
            @endif
        </div>
    </div>
</div>
@endsection

resources/views/people/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">Persoon wijzigen</div>

                <div class="panel-body">
                    
                    {!! Form::model($person ,array('route'=>['person.update', $person->id],'method'=>'PUT')) !!}
                    <div class="form-group">
                        {!! Form::label('first_name','Voornaam')!!}
                        {!! Form::text('first_name', null, ['class'=>'form-control']) !!}
                    </div>
                    <div class="form-group">
                        {!! Form::label('last_name','Achternaam')!!}
                        {!! Form::text('last_name', null, ['class'=>'form-control']) !!}
                    </div>
                    <div class="form-group">
                        {!! Form::label('email','Email')!!}
                        {!! Form::text('email', null, ['class'=>'form-control']) !!}
                    </div>
                    <div class="form-group">
                        {!! Form::label('address1','Adres 1')!!}
                        {!! Form::text('address1', null, ['class'=>'form-control']) !!}
                    </div>
                    <div class="form-group">
                        {!! Form::label('address2','Adres 2')!!}
                        {!! Form::text('address2', null,['class'=>'form-control']) !!}
                    </div>
                    <div class="form-group">
                        {!! Form::label('postalcode','Postcode')!!}
                        {!! Form::text('postalcode', null, ['class'=>'form-control']) !!}
                    </div>
                    <div class="form-group">
                        {!! Form::label('city','Stad')!!}
                        {!! Form::text('city', null, ['class'=>'form-control']) !!}
                    </div>
                    <div class="form-group">
                        {!! Form::label('country','Land')!!}
                        {!! Form::select('country_id', $countries, null, ['class'=>'form-control']) !!}
                    </div>
                    <div class="form-group">
                        {!! Form::label('phone1','Telefoon')!!}
                        {!! Form::text('phone1', null, ['class'=>'form-control']) !!}
                    </div>
                    <div class="form-group">
                        {!! Form::label('birthday','Geboortedatum')!!}
                        {!! Form::date('birthday', null, ['class'=>'form-control']) !!}
                    </div>
                    
                    <div class="form-group">
                        {!! Form::button('Update',['type'=>'submit','class'=>'btn btn-primary'])!!}
                        
                    </div>
                    
                    
                    {!! Form::close() !!}
                
              </div>
            </div>
            @if($errors->has())
                <ul class="alert alert-danger">
                @foreach($errors->all() as $error)
                    <li>{{$error}}</li>
                @endforeach
                </ul>
            @endif
        </div>
    </div>
</div>
@endsection

resources/views/people/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">Personen</div>

                <div class="panel-body">
                    
                    <table class="table">
                    <tr>
                        <th>Voornaam</th>
                        <th>Achternaam</th>
                    </tr>
                    @foreach($people as $person)
                    <tr>
                        <td>{{$person->first_name}}</td>
                        <td>{{$person->last_name}}</td>
                        <td>
                            {{ link_to_route('person.show', 'Details', [$person->id], ['class'=>'btn btn-primary']) }}
                        </td>
                    </tr>
                    @endforeach
                 </table>
                
              </div>
            </div>
            {{ link_to_route('person.create', 'Nieuw persoon toevoegen', null,['class'=>'btn btn-success']) }}
        </div>
    </div>
</div>
@endsection

resources/views/people/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">Details</div>

                <div class="panel-body">
                    
                    {!! Form::open(array('route'=>['person.destroy',$person->id], 'method'=>'DELETE')) !!}
                    <div class="form-group">
                        {!! Form::label('first_name','Voornaam')!!}
                        {!! Form::text('first_name', $person->first_name, ['class'=>'form-control', 'readonly' => true]) !!}
                    </div>
                    <div class="form-group">
                        {!! Form::label('last_name','Achternaam')!!}
                        {!! Form::text('last_name', $person->last_name, ['class'=>'form-control', 'readonly' => true]) !!}
                    </div>
                    <div class="form-group">
                        {!! Form::label('email','Email')!!}
                        {!! Form::text('email', $person->email, ['class'=>'form-control', 'readonly' => true]) !!}
                    </div>
                    <div class="form-group">
                        {!! Form::label('address1','Adres 1')!!}
                        {!! Form::text('address1', $person->address1, ['class'=>'form-control', 'readonly' => true]) !!}
                    </div>
                    <div class="form-group">
                        {!! Form::label('address2','Adres 2')!!}
                        {!! Form::text('address2', $person->address2,['class'=>'form-control', 'readonly' => true]) !!}
                    </div>
                    <div class="form-group">
                        {!! Form::label('postalcode','Postcode')!!}
                        {!! Form::text('postalcode', $person->postalcode, ['class'=>'form-control', 'readonly' => true]) !!}
                    </div>
                    <div class="form-group">
                        {!! Form::label('city','Stad')!!}
                        {!! Form::text('city', $person->city, ['class'=>'form-control', 'readonly' => true]) !!}
                    </div>
                    <div class="form-group">
                        {!! Form::label('country','Land')!!}
                        {!! Form::text('country', $person->getCountryName(), ['class'=>'form-control', 'readonly' => true]) !!}
                    </div>
                    <div class="form-group">
                        {!! Form::label('phone1','Telefoon')!!}
                        {!! Form::text('phone1', $person->phone1, ['class'=>'form-control', 'readonly' => true]) !!}
                    </div>
                    <div class="form-group">
                        {!! Form::label('birthday','Geboortedatum')!!}
                        {!! Form::date('birthday', $person->birthday, ['class'=>'form-control', 'readonly' => true]) !!}
                    </div>
                    
                    <div class="form-group">
                        {{ link_to_route('person.index', 'Terug', null,['class'=>'btn btn-primary']) }}
                        |
                        {{ link_to_route('person.edit', 'Wijzig', [$person->id],['class'=>'btn btn-primary']) }}
                        |
                        {!! Form::button('Verwijder', ['class'=>'btn btn-danger','type'=>'submit']) !!}
                        
                    </div>
                    {!! Form::close() !!}
                
              </div>
            </div>
        </div>
    </div>
</div>
@endsection